volumes:
  mysql_data:

services:
  # Backend API
  tds_backend:
    container_name: tds_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    environment:
      # Override untuk Docker environment
      DB_HOST: 10.184.0.36
      DB_PORT: 3306
      DB_NAME: tds
      DB_USER: root
      DB_PASSWORD: 28112016
      GIN_MODE: release
    ports:
      - "8122:8080"
    networks:
      - tds-net

  # Frontend
  tds_frontend:
    container_name: tds_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./frontend/.env
    environment:
      # Override untuk Docker environment
      NODE_ENV: production
      # Client-side API calls (browser to backend via reverse proxy)
      NEXT_PUBLIC_API_ENDPOINT: https://pe.spil.co.id
      HOST: "0.0.0.0"
      PORT: 3000
    ports:
      - "8121:3000"
    depends_on:
      - tds_backend
    networks:
      - tds-net

networks:
  tds-net:
    name: tds-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.51.0/24
          gateway: 172.19.51.1
