networks:
  spil_tds:
    driver: bridge

services:
  tds_frontend:
    container_name: tds_frontend
    build:
      context: .
      dockerfile: docker/nextjs.dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - spil_tds

  tds_backend:
    container_name: tds_backend
    build:
      context: .
      dockerfile: docker/golang.dockerfile
    restart: always
    environment:
      - GIN_MODE=release
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - ./backend:/app
    networks:
      - spil_tds
    ports:
      - "8080:8090"
    deploy:
      restart_policy:
        condition: on-failure
