version: "3.8"

volumes:
  backend_storage:
  # jangan mount .next ke named volume di dev
  # frontend_public:

services:
  tds_backend:
    container_name: tds_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql-container # pastikan nama ini sama dengan container mysql kamu
      DB_PORT: 3306
      DB_USER: tds_user
      DB_PASSWORD: tds_pass
      DB_NAME: tds
      GIN_MODE: release
    ports:
      - "8080:8080"
    volumes:
      - backend_storage:/app/storage
      - ./backend/public:/app/public:ro
    networks:
      - tds-net

  tds_frontend:
    container_name: tds_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Pass environment variables ke build stage
        NEXT_PUBLIC_API_ENDPOINT: http://localhost:8080
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
      # Untuk runtime di dalam container, gunakan internal address
      NEXT_PUBLIC_API_ENDPOINT: http://localhost:8080
      HOSTNAME: "0.0.0.0"
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      # dev: bind-mount project agar hot reload
      - ./frontend:/app
      - /app/node_modules # menghindari override node_modules host
    depends_on:
      - tds_backend
    networks:
      - tds-net

networks:
  tds-net:
    driver: bridge
