import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import { usePostAssessment } from "./_hooks/useAssessment";

interface AddAssessmentDialogProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  onSuccess?: () => void;
}

export default function AddAssessmentDialog({
  open,
  setOpen,
  onSuccess,
}: AddAssessmentDialogProps) {
  const [role, setRole] = useState("");
  const [assessmentName, setAssessmentName] = useState("");
  const [usingTimer, setUsingTimer] = useState(false);
  const [timerLimitMinutes, setTimerLimitMinutes] = useState(60);
  const [loading, setLoading] = useState(false);

  const postAssessmentMutation = usePostAssessment();

  const handleSubmit = async () => {
    // Validation
    if (!role.trim()) {
      toast.error("Nama Posisi/Role tidak boleh kosong");
      return;
    }

    setLoading(true);
    try {
      await postAssessmentMutation.mutateAsync({
        id: 0, // Will be generated by backend
        role: role.trim(),
        assessmentName: assessmentName.trim() || undefined,
        usingTimer,
        timerLimitMinutes: usingTimer ? timerLimitMinutes : 0,
      });

      toast.success("Assessment berhasil ditambahkan");
      handleClose();
      if (onSuccess) {
        onSuccess();
      }
    } catch (error) {
      toast.error("Gagal menambahkan assessment");
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setRole("");
    setAssessmentName("");
    setUsingTimer(false);
    setTimerLimitMinutes(60);
    setOpen(false);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Tambah Assessment Baru</DialogTitle>
          <DialogDescription>
            Buat assessment baru untuk posisi/role tertentu
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Role Input */}
          <div className="space-y-2">
            <Label htmlFor="role" className="text-sm font-medium">
              Nama Posisi/Role <span className="text-red-500">*</span>
            </Label>
            <Input
              id="role"
              placeholder="Contoh: Nahkoda, Kepala Kabin, dll"
              value={role}
              onChange={(e) => setRole(e.target.value)}
              disabled={loading}
            />
            <p className="text-xs text-gray-500">
              Masukkan nama posisi atau role yang akan dievaluasi
            </p>
          </div>

          {/* Assessment Name Input */}
          <div className="space-y-2">
            <Label htmlFor="assessmentName" className="text-sm font-medium">
              Nama Assessment
            </Label>
            <Input
              id="assessmentName"
              placeholder="Contoh: Penilaian Nahkoda 2024, dll"
              value={assessmentName}
              onChange={(e) => setAssessmentName(e.target.value)}
              disabled={loading}
            />
            <p className="text-xs text-gray-500">
              (Opsional) Nama deskriptif untuk assessment ini
            </p>
          </div>

          {/* Timer Option */}
          <div className="space-y-3 border-t pt-4">
            <div className="flex items-center gap-3">
              <Checkbox
                id="usingTimer"
                checked={usingTimer}
                onCheckedChange={(checked) => setUsingTimer(checked as boolean)}
                disabled={loading}
              />
              <Label htmlFor="usingTimer" className="text-sm font-medium">
                Gunakan Waktu Terbatas
              </Label>
            </div>

            {/* Timer Limit Input - Shown when usingTimer is true */}
            {usingTimer && (
              <div className="space-y-2 ml-6">
                <Label htmlFor="timerLimit" className="text-sm font-medium">
                  Batas Waktu (Menit)
                </Label>
                <Input
                  id="timerLimit"
                  type="number"
                  min="1"
                  max="480"
                  value={timerLimitMinutes}
                  onChange={(e) =>
                    setTimerLimitMinutes(parseInt(e.target.value))
                  }
                  disabled={loading}
                />
                <p className="text-xs text-gray-500">
                  Waktu maksimal yang diberikan untuk mengerjakan assessment
                </p>
              </div>
            )}
          </div>
        </div>

        <DialogFooter className="flex gap-2">
          <Button variant="outline" onClick={handleClose} disabled={loading}>
            Batal
          </Button>
          <Button onClick={handleSubmit} disabled={loading}>
            {loading ? "Menyimpan..." : "Simpan Assessment"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
