// Dataset benchmark resmi operasional maritim PT SPIL untuk instant preview & demo mentor
export interface SpreadsheetRow {
  id: string;
  name: string;
  rank: string;
  department: "DECK" | "ENGINE" | "CATERING" | "TRAINEE" | "GENERAL";
  vessel: string;
  score: number;
  status: "Sangat Baik" | "Baik" | "Cukup" | "Perlu Pembinaan";
  date: string;
  notes: string;
  [key: string]: any;
}

export const PRELOADED_SPIL_DATASET: SpreadsheetRow[] = [
  {
    id: "SPIL-001",
    name: "Capt. Bambang Suryadi",
    rank: "NAKHODA",
    department: "DECK",
    vessel: "KM SPIL CITRA",
    score: 92,
    status: "Sangat Baik",
    date: "2026-01-15",
    notes: "Leadership & navigasi alur sempit sangat kompeten, zero incident",
  },
  {
    id: "SPIL-002",
    name: "Agus Prasetyo",
    rank: "KKM",
    department: "ENGINE",
    vessel: "KM SPIL CITRA",
    score: 89,
    status: "Sangat Baik",
    date: "2026-01-18",
    notes: "Pemeliharaan main engine & auxiliary engine efisien, konsumsi BBM optimal",
  },
  {
    id: "SPIL-003",
    name: "Dedi Kurniawan",
    rank: "MUALIM I",
    department: "DECK",
    vessel: "KM SPIL NIKEN",
    score: 84,
    status: "Baik",
    date: "2026-01-20",
    notes: "Stowage planning container & penanganan muatan berbahaya (DG) tepat waktu",
  },
  {
    id: "SPIL-004",
    name: "Hendra Wijaya",
    rank: "MASINIS I",
    department: "ENGINE",
    vessel: "KM SPIL NIKEN",
    score: 86,
    status: "Sangat Baik",
    date: "2026-01-22",
    notes: "Troubleshooting sistem hidrolik crane kapal handal",
  },
  {
    id: "SPIL-005",
    name: "Rizky Ramadhan",
    rank: "MUALIM II",
    department: "DECK",
    vessel: "KM SPIL HASNA",
    score: 78,
    status: "Baik",
    date: "2026-02-01",
    notes: "Update chart ECDIS & administrasi voyage plan terorganisir",
  },
  {
    id: "SPIL-006",
    name: "Eko Wahyudi",
    rank: "MASINIS II",
    department: "ENGINE",
    vessel: "KM SPIL HASNA",
    score: 81,
    status: "Baik",
    date: "2026-02-03",
    notes: "Manajemen purifier bahan bakar dan pelumas stabil",
  },
  {
    id: "SPIL-007",
    name: "Ahmad Fauzi",
    rank: "MUALIM III",
    department: "DECK",
    vessel: "KM SPIL RUMAN",
    score: 74,
    status: "Baik",
    date: "2026-02-05",
    notes: "Pemeliharaan peralatan keselamatan (LSA/FFA) sesuai SOLAS",
  },
  {
    id: "SPIL-008",
    name: "Bayu Saputra",
    rank: "MASINIS III",
    department: "ENGINE",
    vessel: "KM SPIL RUMAN",
    score: 72,
    status: "Baik",
    date: "2026-02-08",
    notes: "Pengoperasian boiler dan fresh water generator lancar",
  },
  {
    id: "SPIL-009",
    name: "Joko Susilo",
    rank: "ELECTRICIAN",
    department: "ENGINE",
    vessel: "KM SPIL CITRA",
    score: 88,
    status: "Sangat Baik",
    date: "2026-02-10",
    notes: "Perbaikan sistem kelistrikan reefer container cepat dan akurat",
  },
  {
    id: "SPIL-010",
    name: "Slamet Riyadi",
    rank: "SERANG",
    department: "DECK",
    vessel: "KM SPIL CITRA",
    score: 76,
    status: "Baik",
    date: "2026-02-12",
    notes: "Pengawasan kerja dek dan mooring operation rapi",
  },
  {
    id: "SPIL-011",
    name: "Teguh Santoso",
    rank: "MANDOR MESIN",
    department: "ENGINE",
    vessel: "KM SPIL NIKEN",
    score: 79,
    status: "Baik",
    date: "2026-02-14",
    notes: "Manajemen kerja rating mesin dan housekeeping kamar mesin tertib",
  },
  {
    id: "SPIL-012",
    name: "Wawan Hermawan",
    rank: "JURU MUDI",
    department: "DECK",
    vessel: "KM SPIL NIKEN",
    score: 68,
    status: "Cukup",
    date: "2026-02-15",
    notes: "Perlu peningkatan pemahaman prosedur lookout navigasi malam hari",
  },
  {
    id: "SPIL-013",
    name: "Fajar Nugraha",
    rank: "JURU MINYAK",
    department: "ENGINE",
    vessel: "KM SPIL HASNA",
    score: 67,
    status: "Cukup",
    date: "2026-02-17",
    notes: "Perlu pengawasan saat sounding tanki dan pembersihan filter",
  },
  {
    id: "SPIL-014",
    name: "Rudi Hartono",
    rank: "JURU MASAK I",
    department: "CATERING",
    vessel: "KM SPIL CITRA",
    score: 85,
    status: "Sangat Baik",
    date: "2026-02-18",
    notes: "Higiene makanan & gizi kru kapal terjaga, manajemen logistik prima",
  },
  {
    id: "SPIL-015",
    name: "Budi Setiawan",
    rank: "PELAYAN",
    department: "CATERING",
    vessel: "KM SPIL NIKEN",
    score: 73,
    status: "Baik",
    date: "2026-02-20",
    notes: "Kebersihan mess room dan akomodasi kru terpelihara",
  },
  {
    id: "SPIL-016",
    name: "Dimas Anggara",
    rank: "KADET DEK",
    department: "TRAINEE",
    vessel: "KM SPIL CITRA",
    score: 70,
    status: "Baik",
    date: "2026-02-22",
    notes: "Proaktif mempelajari log book navigasi dan radio telephony",
  },
  {
    id: "SPIL-017",
    name: "Arif Hidayat",
    rank: "KADET MESIN",
    department: "TRAINEE",
    vessel: "KM SPIL HASNA",
    score: 65,
    status: "Cukup",
    date: "2026-02-24",
    notes: "Perlu bimbingan lebih dalam pembacaan manual book permesinan",
  },
  {
    id: "SPIL-018",
    name: "Yusuf Maulana",
    rank: "KELASI",
    department: "DECK",
    vessel: "KM SPIL RUMAN",
    score: 58,
    status: "Perlu Pembinaan",
    date: "2026-02-25",
    notes: "Perlu pelatihan ulang pengikatan lashing kontainer & keselamatan kerja",
  },
  {
    id: "SPIL-019",
    name: "Supriadi",
    rank: "FITTER",
    department: "ENGINE",
    vessel: "KM SPIL CITRA",
    score: 87,
    status: "Sangat Baik",
    date: "2026-02-26",
    notes: "Kemampuan pengelasan & fabrikasi pipa di atas kapal sangat memuaskan",
  },
  {
    id: "SPIL-020",
    name: "Capt. Irwan Susanto",
    rank: "PORT CAPTAIN",
    department: "GENERAL",
    vessel: "DARAT / HEAD OFFICE",
    score: 94,
    status: "Sangat Baik",
    date: "2026-02-28",
    notes: "Supervisi port operation dan koordinasi pandu pelabuhan sangat efektif",
  },
];
